import React, { Suspense, lazy } from 'react';
import ReactDOM from 'react-dom/client';
import './globals.css';

// Route manifest generated by the Vula CLI
// @ts-ignore
import manifest from '../.vula-routes.json';

function Router() {
  const pathname = window.location.pathname;

  const route =
    manifest.routes.find((r: any) => r.path === pathname) ||
    manifest.routes.find((r: any) => r.path === '/');

  if (!route) {
    return (
      <div style={{ padding: '4rem', textAlign: 'center', fontFamily: 'system-ui' }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>404</h1>
        <p>Page not found.</p>
      </div>
    );
  }

  // Resolve component path relative to the @app alias
  const relativePath = route.componentPath.split('app')[1];
  const Component = lazy(() => import(`@app${relativePath}`));

  return (
    <Suspense fallback={<div style={{ padding: '2rem', textAlign: 'center' }}>Loading...</div>}>
      <Component />
    </Suspense>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root')!);
root.render(
  <React.StrictMode>
    <Router />
  </React.StrictMode>
);
